NUMBER_OF_CLASSES = 29
NUMBER_OF_IMAGES = 87000
IMAGE_DIMENSION = 200
CLASSES = ['A', 'B', 'C', 'D', 'del', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'nothing', 'O', 'P', 'Q', 'R', 'S', 'space',
           'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

INPUT_SHAPE = (64, 64, 3)
NUMBER_OF_FILTERS_1 = 32
NUMBER_OF_FILTERS_2 = 64
NUMBER_OF_FILTERS_3 = 128
NUMBER_OF_FILTERS_4 = 256
KERNEL_SIZE = 3
STRIDES = (1, 1)
ACTIVATION_FUNCTION = 'relu'
POOL_SIZE = 3
DROPOUT_RATE = 0.5
DENSE_UNITS = 512
SECOND_ACTIVATION_FUNCTION = 'softmax'