MAIN_WINDOW_STYLE_SHEET = "background-color: #493fda;"
MAIN_BUTTON_STYLE_SHEET = "border-radius: 15px;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;\n"
"background-color: white;\n"
"hover {\n"
"  background-color: #4CAF50;\n"
"  color: white;\n"
"}"